### ISSUE TITLE
llegal string offset 'file'

### ISSUE THREAD

**Issue by iandevlin** [kylereicks/picturefill.js.wp#60]
I'm currently getting a number of these warnings on a page, all stemming from the fact that `wp_get_attachment_metadata($attachment_id);` is returning as empty, in the `set_image_attachment_data` method of `class-model-image-picturefill-wp.php`.

I tried ignoring the subsequent code within the method if this returns as empty, but this breaks something else further on in the chain.

Since it's only a warning, it might be ok to just supress it, but again, you would know best.

Any suggestions here would be greatly appreciated again.

**Comment by tychay** [comment]
That shouldn't happen. Or rather, it's assumed it shouldn't happen.

I looked into the WordPress core codebase, and my best guess is one of two things are going on:

1. the attachments being accessed were uploaded pre WordPress 2.3 and thus don't have any attachment metadata associated with it. You can fix it by calling wp_maybe_generate_attachment_metadata() on all your attachments (maybe there's a plugin out there that does this)?
2. the attachment is missing a file or the file associated with it isn't an image. This shouldn't happen since only image files should generate image tags, but it is conceivable if a plugin is emulating attachment and added image support improperly (for instance, a plugin that tries to hack in post_thumbnails will run into this as the core code for images and attachments is spaghetti ("media" "attachment" and "image" files and concepts are commingled.)

**Comment by iandevlin** [comment]
I have given up on this plugin, I initially failed to see that the author isn't supporting it anymore. Thanks for you comment nonetheless.
